### PR TITLE
Added (entity) file attachments classes, and wrapper/listwrappers

### PR DESCRIPTION
**Pull request by mcrichton**
Required for Dataloader fork development

### CODE REVIEW

**Comment by johnsully83** [comment]
Let's annotate our properties with Jackson annotations at the method level as well as the property level

**Comment by mcrichton** [comment]
Oh, sorry! I didn't get a notification when you replied. 

I don't really know anything about the annotations, I just made these to fix a problem we were having. I thought you might want them as a starting point. I thought they worked okay at the time, should they not have? The reference PDF says the fields are read-only, do I need to add "@ReadOnly" everywhere? I've been hurt trusting the reference before, I would kinda rather the user decide than bake in something that was wrong

**Comment by johnsully83** [comment]
check out
https://github.com/bullhorn/sdk-rest/blob/master/src/main/java/com/bullhornsdk/data/model/entity/core/standard/Candidate.java

you can see in addition to the
@JsonPropertyOrder
annotation we have at the class level, we also have
@JsonProperty
annotations on every getter and setter, indicating which property the getter and setter is for.  This is all I was referring to, would be adding in these @JsonProperty annotations

**Comment by mcrichton** [comment]
Gotcha. Will do!

**Comment by johnsully83** [comment]
Other thing we'll want to do is add unit tests.  This typically would consist of adding in properties file similar to the ones in 

https://github.com/bullhorn/sdk-rest/tree/master/src/test/resources/testdata/rest

and then modifying some of the classes in 

https://github.com/bullhorn/sdk-rest/tree/master/src/main/java/com/bullhornsdk/data/api/mock

to make sure they pick up the file.  Then you'll finally want to add in the unit tests themselves (typically we add one for every CRUD operation, as well as query/search that the new entity(s) support)

**Comment by mcrichton** [comment]
Sorry, I forgot all about this! As it turns out, I'm not going to have time to finish this branch -- since my current implementation (injecting these into the official SDK) works regardless, I've been told to prioritise other things (which I don't think is changing anytime soon ☹ ).

**Comment by mcrichton** [comment]
@johnsully83 Finally got back to it! I hope this is sufficient. I wasn't too sure what to do in the way of tests. There is also one "FIXME," because I didn't add the full 20 records for each entity. We don't have enough on our development sandbox for me to export a full set, and I didn't want to make them by hand!

**Comment by mcrichton** [comment]
Or @rmcdole / @monroepe 😊

**Comment by johnsully83** [comment]
@mcrichton to complete the testdata files, we typically just copy the records we do have and change the ids, so if you only had one entity and you're JSON looked like

{
    "total": 1,
    "start": 0,
    "count": 1,
    "data": [
        {
            "id": 1,
            "candidate": {
                "id": 1,
                "firstName": "Joe",
                "lastName": "Smith"
            },
            "clientContact": {
                "id": 1,
                "firstName": "HC Barack",
                "lastName": "Obama"
            },
            "clientCorporation": {
                "id": 1,
                "name": "testcompany"
            },
            "dateAdded": 1375216791760,
            "email": null,
            "isRead": false,
            "jobOrder": {
                "id": 1,
                "title": "tester job title"
            },
            "migrateGUID": null,
            "user": {
                "id": 1
            }
        }
    ]
}

I would just copy the

{
            "id": 1,
            "candidate": {
                "id": 1,
                "firstName": "Joe",
                "lastName": "Smith"
            },
            "clientContact": {
                "id": 1,
                "firstName": "HC Barack",
                "lastName": "Obama"
            },
            "clientCorporation": {
                "id": 1,
                "name": "testcompany"
            },
            "dateAdded": 1375216791760,
            "email": null,
            "isRead": false,
            "jobOrder": {
                "id": 1,
                "title": "tester job title"
            },
            "migrateGUID": null,
            "user": {
                "id": 1
            }
        } 

section 19 times, and manually change the IDs for all of those entities to 1-20

Once we do that we can merge in and release

**Comment by mcrichton** [comment]
@johnsully83 Sorry, I meant to notify you when the tests finished, but they take for_ever_. I think it's good to go, unless you see any other problems?

**Pull request merged**
