### PR TITLE
Sign of life from California.

### PR DESCRIPTION
**Pull request by magnusfiorepalm**
Updating the README to point out the extensive self documenting unit tests.

### CODE REVIEW

**Comment by magnusfiorepalm** [comment]
Hey @johnsully83, glad to see you guys are getting this open sourced. Small detail, you've got a type in "Plaftorm".

**Comment by TheReal** [comment]
Awesome to hear from you @magnusfiorepalm ! Hope live is treating you well in Cali. Fixed up the headline typo; thanks for that.

**Comment by TheReal** [comment]
@johnsully83 LGTM. Do the necessaries.

**Comment by magnusfiorepalm** [comment]
@TheReal @johnsully83 Glad to see the SDK getting open sourced!

**Comment by johnsully83** [comment]
Thanks @magnusfiorepalm !  Exciting times!

**Pull request merged**
